export const STACK_ID_DEFAULT: string = 'proj-id-default'
export const STACK_PREFIX: string = 'proj-demo'
export const RESOURCE_PREFIX: string = 'proj'
export const BRANCH_NAME_DEFAULT: string = 'branch-name-default'
export const RESOURCE_ID_DEFAULT: string = 'resource-id-default'
export const TEAM_NAME: string = 'proj-demo-team'
